# Generated by Django 3.2.4 on 2021-07-12 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='None.jpg', upload_to='static/Bmeste/profile_img')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('default_location_lat', models.FloatField(default=0)),
                ('default_location_lng', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bmeste.author')),
            ],
        ),
        migrations.CreateModel(
            name='Piece_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_detail', models.CharField(default='', max_length=200)),
                ('location_lat', models.FloatField(default=0)),
                ('location_lng', models.FloatField(default=0)),
                ('description', models.TextField(default='', max_length=200)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bmeste.piece')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('comment_text', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bmeste.piece')),
            ],
        ),
        migrations.CreateModel(
            name='Author_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_detail', models.CharField(default='', max_length=200)),
                ('location_lat', models.FloatField(default=0)),
                ('location_lng', models.FloatField(default=0)),
                ('description', models.TextField(default='', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bmeste.author')),
            ],
        ),
    ]
