# Generated by Django 3.2.4 on 2021-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(default='None.jpg', upload_to='static/Bmeste/profile_img'),
        ),
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
