# Generated by Django 3.2.4 on 2021-07-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0002_alter_comment_piece_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_piece',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment_piece',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bmeste.piece'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
