# Generated by Django 3.2.4 on 2021-06-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0003_auto_20210613_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pieces',
            new_name='Piece',
        ),
        migrations.CreateModel(
            name='Piece_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_detail', models.CharField(default='', max_length=200)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bmeste.piece')),
            ],
        ),
    ]
