# Generated by Django 3.2.4 on 2021-07-13 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0003_auto_20210713_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_piece',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='comment_piece',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment_piece',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='comment_piece',
            name='writer_name',
        ),
        migrations.AddField(
            model_name='comment_piece',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Bmeste.piece'),
        ),
        migrations.AddField(
            model_name='comment_piece',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='comment_piece',
            name='comment_user',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment_piece',
            name='comment_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment_piece',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
