# Generated by Django 3.2.4 on 2021-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0004_auto_20210713_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_piece',
            old_name='comment',
            new_name='piece',
        ),
        migrations.AlterField(
            model_name='comment_piece',
            name='comment_text',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
