# Generated by Django 3.2.4 on 2021-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0005_auto_20210619_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='default_location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='default_location_lng',
            field=models.FloatField(default=0),
        ),
    ]
