# Generated by Django 3.2.4 on 2021-08-01 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0005_auto_20210713_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='birth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
