# Generated by Django 3.2.4 on 2021-06-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0006_auto_20210619_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece_detail',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='piece_detail',
            name='piece_detail',
            field=models.TextField(default='', max_length=200),
        ),
    ]
