# Generated by Django 3.2.4 on 2021-08-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0006_auto_20210801_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_rus',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='piece',
            name='title_rus',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
