# Generated by Django 3.2.4 on 2021-06-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0007_auto_20210622_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece_detail',
            name='piece_detail',
            field=models.TextField(default='', max_length=200, verbose_name='piece_detail'),
        ),
    ]
