# Generated by Django 3.2.4 on 2021-08-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0008_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece_detail',
            name='piece_detail_rus',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='piece_detail',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Author_detail',
        ),
    ]
