# Generated by Django 3.2.4 on 2021-06-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0008_alter_piece_detail_piece_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece_detail',
            name='piece_detail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
