# Generated by Django 3.2.4 on 2021-08-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0009_auto_20210805_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='default_location_zoom',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='piece_detail',
            name='location_h',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='piece_detail',
            name='location_t',
            field=models.FloatField(default=0),
        ),
    ]
