# Generated by Django 3.2.4 on 2021-08-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bmeste', '0010_auto_20210808_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece_detail',
            old_name='location_h',
            new_name='location_heading',
        ),
        migrations.RenameField(
            model_name='piece_detail',
            old_name='location_t',
            new_name='location_pitch',
        ),
    ]
